/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2020-07-27 19:09:43 EDT)
 * on 2020-07-27 at 23:09:44 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * A conversational entity that represents a brand.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Agent extends com.google.api.client.json.GenericJson {

  /**
   * Detailed agent information for Business Messages.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private BusinessMessagesAgent businessMessagesAgent;

  /**
   * Required. The name that the agent displays to users. Maximum 40 characters.
   *
   * Not modifiable after agent verification.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String displayName;

  /**
   * The unique identifier of the agent.
   *
   * Read-only. Defined by the platform.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * Detailed agent information for Verified SMS.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private VerifiedSmsAgent verifiedSmsAgent;

  /**
   * Detailed agent information for Business Messages.
   * @return value or {@code null} for none
   */
  public BusinessMessagesAgent getBusinessMessagesAgent() {
    return businessMessagesAgent;
  }

  /**
   * Detailed agent information for Business Messages.
   * @param businessMessagesAgent businessMessagesAgent or {@code null} for none
   */
  public Agent setBusinessMessagesAgent(BusinessMessagesAgent businessMessagesAgent) {
    this.businessMessagesAgent = businessMessagesAgent;
    return this;
  }

  /**
   * Required. The name that the agent displays to users. Maximum 40 characters.
   *
   * Not modifiable after agent verification.
   * @return value or {@code null} for none
   */
  public java.lang.String getDisplayName() {
    return displayName;
  }

  /**
   * Required. The name that the agent displays to users. Maximum 40 characters.
   *
   * Not modifiable after agent verification.
   * @param displayName displayName or {@code null} for none
   */
  public Agent setDisplayName(java.lang.String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * The unique identifier of the agent.
   *
   * Read-only. Defined by the platform.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * The unique identifier of the agent.
   *
   * Read-only. Defined by the platform.
   * @param name name or {@code null} for none
   */
  public Agent setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * Detailed agent information for Verified SMS.
   * @return value or {@code null} for none
   */
  public VerifiedSmsAgent getVerifiedSmsAgent() {
    return verifiedSmsAgent;
  }

  /**
   * Detailed agent information for Verified SMS.
   * @param verifiedSmsAgent verifiedSmsAgent or {@code null} for none
   */
  public Agent setVerifiedSmsAgent(VerifiedSmsAgent verifiedSmsAgent) {
    this.verifiedSmsAgent = verifiedSmsAgent;
    return this;
  }

  @Override
  public Agent set(String fieldName, Object value) {
    return (Agent) super.set(fieldName, value);
  }

  @Override
  public Agent clone() {
    return (Agent) super.clone();
  }

}
