/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2021-09-08 15:02:56 EDT)
 * on 2021-09-08 at 19:02:57 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * Approval details composed from the state and optional additional information.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ApprovalDetails extends com.google.api.client.json.GenericJson {

  /**
   * Output only. Additional information about the decision, if available.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String approvalInfo;

  /**
   * Output only. The current approval state.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String approvalState;

  /**
   * Output only. Additional information about the decision, if available.
   * @return value or {@code null} for none
   */
  public java.lang.String getApprovalInfo() {
    return approvalInfo;
  }

  /**
   * Output only. Additional information about the decision, if available.
   * @param approvalInfo approvalInfo or {@code null} for none
   */
  public ApprovalDetails setApprovalInfo(java.lang.String approvalInfo) {
    this.approvalInfo = approvalInfo;
    return this;
  }

  /**
   * Output only. The current approval state.
   * @return value or {@code null} for none
   */
  public java.lang.String getApprovalState() {
    return approvalState;
  }

  /**
   * Output only. The current approval state.
   * @param approvalState approvalState or {@code null} for none
   */
  public ApprovalDetails setApprovalState(java.lang.String approvalState) {
    this.approvalState = approvalState;
    return this;
  }

  @Override
  public ApprovalDetails set(String fieldName, Object value) {
    return (ApprovalDetails) super.set(fieldName, value);
  }

  @Override
  public ApprovalDetails clone() {
    return (ApprovalDetails) super.clone();
  }

}
