/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2022-10-18 16:21:26 UTC)
 * on 2022-10-18 at 16:21:49 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * Call reason with approval information.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CallReason extends com.google.api.client.json.GenericJson {

  /**
   * Output only. Approval details; each call reason must be approved before use.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ApprovalDetails approvalDetails;

  /**
   * Immutable. The actual text of the call reason.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String text;

  /**
   * Output only. Approval details; each call reason must be approved before use.
   * @return value or {@code null} for none
   */
  public ApprovalDetails getApprovalDetails() {
    return approvalDetails;
  }

  /**
   * Output only. Approval details; each call reason must be approved before use.
   * @param approvalDetails approvalDetails or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public CallReason setApprovalDetails(ApprovalDetails approvalDetails) {
    this.approvalDetails = approvalDetails;
    return this;
  }

  /**
   * Immutable. The actual text of the call reason.
   * @return value or {@code null} for none
   */
  public java.lang.String getText() {
    return text;
  }

  /**
   * Immutable. The actual text of the call reason.
   * @param text text or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public CallReason setText(java.lang.String text) {
    this.text = text;
    return this;
  }

  @Override
  public CallReason set(String fieldName, Object value) {
    return (CallReason) super.set(fieldName, value);
  }

  @Override
  public CallReason clone() {
    return (CallReason) super.clone();
  }

}
