/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2021-06-24 22:17:16 UTC)
 * on 2021-06-24 at 22:17:25 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * Contact details displayed in addition to the messaging button.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ContactOption extends com.google.api.client.json.GenericJson {

  /**
   * Required. The list of contact options available for the specified URL.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> options;

  /**
   * Required. The URL that contact options are available for.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String url;

  /**
   * Required. The list of contact options available for the specified URL.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getOptions() {
    return options;
  }

  /**
   * Required. The list of contact options available for the specified URL.
   * @param options options or {@code null} for none
   */
  public ContactOption setOptions(java.util.List<java.lang.String> options) {
    this.options = options;
    return this;
  }

  /**
   * Required. The URL that contact options are available for.
   * @return value or {@code null} for none
   */
  public java.lang.String getUrl() {
    return url;
  }

  /**
   * Required. The URL that contact options are available for.
   * @param url url or {@code null} for none
   */
  public ContactOption setUrl(java.lang.String url) {
    this.url = url;
    return this;
  }

  @Override
  public ContactOption set(String fieldName, Object value) {
    return (ContactOption) super.set(fieldName, value);
  }

  @Override
  public ContactOption clone() {
    return (ContactOption) super.clone();
  }

}
