/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2022-09-14 21:13:25 UTC)
 * on 2022-09-14 at 21:13:50 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * Suggested replies shown to users when they enter a conversation with the agent for the first
 * time.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ConversationStarters extends com.google.api.client.json.GenericJson {

  /**
   * Optional. Suggestion at the beginning of a conversation.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Suggestion suggestion;

  /**
   * Optional. Suggestion at the beginning of a conversation.
   * @return value or {@code null} for none
   */
  public Suggestion getSuggestion() {
    return suggestion;
  }

  /**
   * Optional. Suggestion at the beginning of a conversation.
   * @param suggestion suggestion or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public ConversationStarters setSuggestion(Suggestion suggestion) {
    this.suggestion = suggestion;
    return this;
  }

  @Override
  public ConversationStarters set(String fieldName, Object value) {
    return (ConversationStarters) super.set(fieldName, value);
  }

  @Override
  public ConversationStarters clone() {
    return (ConversationStarters) super.clone();
  }

}
