/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2021-09-08 15:02:56 EDT)
 * on 2021-09-08 at 19:02:57 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * Custom survey configuration for an agent.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CustomSurveyConfig extends com.google.api.client.json.GenericJson {

  /**
   * List of custom questions.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<SurveyQuestion> customQuestions;

  /**
   * List of custom questions.
   * @return value or {@code null} for none
   */
  public java.util.List<SurveyQuestion> getCustomQuestions() {
    return customQuestions;
  }

  /**
   * List of custom questions.
   * @param customQuestions customQuestions or {@code null} for none
   */
  public CustomSurveyConfig setCustomQuestions(java.util.List<SurveyQuestion> customQuestions) {
    this.customQuestions = customQuestions;
    return this;
  }

  @Override
  public CustomSurveyConfig set(String fieldName, Object value) {
    return (CustomSurveyConfig) super.set(fieldName, value);
  }

  @Override
  public CustomSurveyConfig clone() {
    return (CustomSurveyConfig) super.clone();
  }

}
