/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2022-10-26 23:10:20 UTC)
 * on 2022-10-26 at 23:10:36 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * A standalone rich card or a carousel of rich cards sent from the agent to the user.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleCommunicationsBusinessmessagesV1RichCard extends com.google.api.client.json.GenericJson {

  /**
   * Carousel of cards.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GoogleCommunicationsBusinessmessagesV1CarouselCard carouselCard;

  /**
   * Standalone card.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GoogleCommunicationsBusinessmessagesV1StandaloneCard standaloneCard;

  /**
   * Carousel of cards.
   * @return value or {@code null} for none
   */
  public GoogleCommunicationsBusinessmessagesV1CarouselCard getCarouselCard() {
    return carouselCard;
  }

  /**
   * Carousel of cards.
   * @param carouselCard carouselCard or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public GoogleCommunicationsBusinessmessagesV1RichCard setCarouselCard(GoogleCommunicationsBusinessmessagesV1CarouselCard carouselCard) {
    this.carouselCard = carouselCard;
    return this;
  }

  /**
   * Standalone card.
   * @return value or {@code null} for none
   */
  public GoogleCommunicationsBusinessmessagesV1StandaloneCard getStandaloneCard() {
    return standaloneCard;
  }

  /**
   * Standalone card.
   * @param standaloneCard standaloneCard or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public GoogleCommunicationsBusinessmessagesV1RichCard setStandaloneCard(GoogleCommunicationsBusinessmessagesV1StandaloneCard standaloneCard) {
    this.standaloneCard = standaloneCard;
    return this;
  }

  @Override
  public GoogleCommunicationsBusinessmessagesV1RichCard set(String fieldName, Object value) {
    return (GoogleCommunicationsBusinessmessagesV1RichCard) super.set(fieldName, value);
  }

  @Override
  public GoogleCommunicationsBusinessmessagesV1RichCard clone() {
    return (GoogleCommunicationsBusinessmessagesV1RichCard) super.clone();
  }

}
