/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2021-06-24 22:17:16 UTC)
 * on 2021-06-24 at 22:17:25 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * Partner that is onboarded with a supported product.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Partner extends com.google.api.client.json.GenericJson {

  /**
   * Optional. The company name of the partner.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String company;

  /**
   * Optional. The list of contact emails.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> contactEmails;

  /**
   * Required. The display name of the partner.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String displayName;

  /**
   * Output only. The unique identifier of the partner. Defined by the platform.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The product capabilities of the partner.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<ProductCapability> productCapabilities;

  /**
   * Optional. The company name of the partner.
   * @return value or {@code null} for none
   */
  public java.lang.String getCompany() {
    return company;
  }

  /**
   * Optional. The company name of the partner.
   * @param company company or {@code null} for none
   */
  public Partner setCompany(java.lang.String company) {
    this.company = company;
    return this;
  }

  /**
   * Optional. The list of contact emails.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getContactEmails() {
    return contactEmails;
  }

  /**
   * Optional. The list of contact emails.
   * @param contactEmails contactEmails or {@code null} for none
   */
  public Partner setContactEmails(java.util.List<java.lang.String> contactEmails) {
    this.contactEmails = contactEmails;
    return this;
  }

  /**
   * Required. The display name of the partner.
   * @return value or {@code null} for none
   */
  public java.lang.String getDisplayName() {
    return displayName;
  }

  /**
   * Required. The display name of the partner.
   * @param displayName displayName or {@code null} for none
   */
  public Partner setDisplayName(java.lang.String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * Output only. The unique identifier of the partner. Defined by the platform.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Output only. The unique identifier of the partner. Defined by the platform.
   * @param name name or {@code null} for none
   */
  public Partner setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * The product capabilities of the partner.
   * @return value or {@code null} for none
   */
  public java.util.List<ProductCapability> getProductCapabilities() {
    return productCapabilities;
  }

  /**
   * The product capabilities of the partner.
   * @param productCapabilities productCapabilities or {@code null} for none
   */
  public Partner setProductCapabilities(java.util.List<ProductCapability> productCapabilities) {
    this.productCapabilities = productCapabilities;
    return this;
  }

  @Override
  public Partner set(String fieldName, Object value) {
    return (Partner) super.set(fieldName, value);
  }

  @Override
  public Partner clone() {
    return (Partner) super.clone();
  }

}
