/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2022-10-18 16:21:26 UTC)
 * on 2022-10-18 at 16:21:49 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * Configuration details for supporting customized survey questions.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SurveyConfig extends com.google.api.client.json.GenericJson {

  /**
   * Custom survey questions for an agent, mapped to a locale. Locale is represented by a well-
   * formed [IETF BCP 47](https://tools.ietf.org/html/bcp47) language tag.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.Map<String, CustomSurveyConfig> customSurveys;

  /**
   * List of template question IDs for template questions included in a survey.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> templateQuestionIds;

  /**
   * Custom survey questions for an agent, mapped to a locale. Locale is represented by a well-
   * formed [IETF BCP 47](https://tools.ietf.org/html/bcp47) language tag.
   * @return value or {@code null} for none
   */
  public java.util.Map<String, CustomSurveyConfig> getCustomSurveys() {
    return customSurveys;
  }

  /**
   * Custom survey questions for an agent, mapped to a locale. Locale is represented by a well-
   * formed [IETF BCP 47](https://tools.ietf.org/html/bcp47) language tag.
   * @param customSurveys customSurveys or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public SurveyConfig setCustomSurveys(java.util.Map<String, CustomSurveyConfig> customSurveys) {
    this.customSurveys = customSurveys;
    return this;
  }

  /**
   * List of template question IDs for template questions included in a survey.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getTemplateQuestionIds() {
    return templateQuestionIds;
  }

  /**
   * List of template question IDs for template questions included in a survey.
   * @param templateQuestionIds templateQuestionIds or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public SurveyConfig setTemplateQuestionIds(java.util.List<java.lang.String> templateQuestionIds) {
    this.templateQuestionIds = templateQuestionIds;
    return this;
  }

  @Override
  public SurveyConfig set(String fieldName, Object value) {
    return (SurveyConfig) super.set(fieldName, value);
  }

  @Override
  public SurveyConfig clone() {
    return (SurveyConfig) super.clone();
  }

}
