/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2020-09-17 08:43:04 EDT)
 * on 2020-09-17 at 12:43:15 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * Agent information specific to Verified SMS.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class VerifiedSmsAgent extends com.google.api.client.json.GenericJson {

  /**
   * Required. Description about the registered agent. The description is visible to end users.
   * Maximum 100 characters.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * Required. The agent logo. Maximum 50 KB.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String logoUrl;

  /**
   * The list of Sender IDs for the Verified SMS agent.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Sender> senders;

  /**
   * Required. Description about the registered agent. The description is visible to end users.
   * Maximum 100 characters.
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * Required. Description about the registered agent. The description is visible to end users.
   * Maximum 100 characters.
   * @param description description or {@code null} for none
   */
  public VerifiedSmsAgent setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * Required. The agent logo. Maximum 50 KB.
   * @return value or {@code null} for none
   */
  public java.lang.String getLogoUrl() {
    return logoUrl;
  }

  /**
   * Required. The agent logo. Maximum 50 KB.
   * @param logoUrl logoUrl or {@code null} for none
   */
  public VerifiedSmsAgent setLogoUrl(java.lang.String logoUrl) {
    this.logoUrl = logoUrl;
    return this;
  }

  /**
   * The list of Sender IDs for the Verified SMS agent.
   * @return value or {@code null} for none
   */
  public java.util.List<Sender> getSenders() {
    return senders;
  }

  /**
   * The list of Sender IDs for the Verified SMS agent.
   * @param senders senders or {@code null} for none
   */
  public VerifiedSmsAgent setSenders(java.util.List<Sender> senders) {
    this.senders = senders;
    return this;
  }

  @Override
  public VerifiedSmsAgent set(String fieldName, Object value) {
    return (VerifiedSmsAgent) super.set(fieldName, value);
  }

  @Override
  public VerifiedSmsAgent clone() {
    return (VerifiedSmsAgent) super.clone();
  }

}
