/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2022-09-14 21:13:25 UTC)
 * on 2022-09-14 at 21:13:50 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * Phone number with approval information.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class VerifiedCallsPhone extends com.google.api.client.json.GenericJson {

  /**
   * Output only. Approval details, each phone number must be approved before use.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ApprovalDetails approvalDetails;

  /**
   * Immutable. Phone number in E.164 format i.e. +18888888888
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String number;

  /**
   * Output only. Approval details, each phone number must be approved before use.
   * @return value or {@code null} for none
   */
  public ApprovalDetails getApprovalDetails() {
    return approvalDetails;
  }

  /**
   * Output only. Approval details, each phone number must be approved before use.
   * @param approvalDetails approvalDetails or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public VerifiedCallsPhone setApprovalDetails(ApprovalDetails approvalDetails) {
    this.approvalDetails = approvalDetails;
    return this;
  }

  /**
   * Immutable. Phone number in E.164 format i.e. +18888888888
   * @return value or {@code null} for none
   */
  public java.lang.String getNumber() {
    return number;
  }

  /**
   * Immutable. Phone number in E.164 format i.e. +18888888888
   * @param number number or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public VerifiedCallsPhone setNumber(java.lang.String number) {
    this.number = number;
    return this;
  }

  @Override
  public VerifiedCallsPhone set(String fieldName, Object value) {
    return (VerifiedCallsPhone) super.set(fieldName, value);
  }

  @Override
  public VerifiedCallsPhone clone() {
    return (VerifiedCallsPhone) super.clone();
  }

}
