/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2022-10-18 16:21:26 UTC)
 * on 2022-10-18 at 16:21:49 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.businesscommunications.v1.model;

/**
 * Agent information specifically related to Verified Calls.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Business Communications. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class VerifiedCallsAgent extends com.google.api.client.json.GenericJson {

  /**
   * Required. Call reasons that this agent may use when placing a verified call. Only add / remove
   * actions are allowed. Each action will be reviewed before the change takes place.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<CallReason> callReasons;

  /**
   * Required. Publicly available URL of the agent logo to display with a verified call. Maximum 50
   * KB. Not modifiable after agent verification.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String logoUrl;

  /**
   * Required. Phone numbers that this agent may use when placing a verified call. Only add / remove
   * actions are allowed. Each action will be reviewed before the change takes place.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<VerifiedCallsPhone> phones;

  /**
   * Required. Call reasons that this agent may use when placing a verified call. Only add / remove
   * actions are allowed. Each action will be reviewed before the change takes place.
   * @return value or {@code null} for none
   */
  public java.util.List<CallReason> getCallReasons() {
    return callReasons;
  }

  /**
   * Required. Call reasons that this agent may use when placing a verified call. Only add / remove
   * actions are allowed. Each action will be reviewed before the change takes place.
   * @param callReasons callReasons or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public VerifiedCallsAgent setCallReasons(java.util.List<CallReason> callReasons) {
    this.callReasons = callReasons;
    return this;
  }

  /**
   * Required. Publicly available URL of the agent logo to display with a verified call. Maximum 50
   * KB. Not modifiable after agent verification.
   * @return value or {@code null} for none
   */
  public java.lang.String getLogoUrl() {
    return logoUrl;
  }

  /**
   * Required. Publicly available URL of the agent logo to display with a verified call. Maximum 50
   * KB. Not modifiable after agent verification.
   * @param logoUrl logoUrl or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public VerifiedCallsAgent setLogoUrl(java.lang.String logoUrl) {
    this.logoUrl = logoUrl;
    return this;
  }

  /**
   * Required. Phone numbers that this agent may use when placing a verified call. Only add / remove
   * actions are allowed. Each action will be reviewed before the change takes place.
   * @return value or {@code null} for none
   */
  public java.util.List<VerifiedCallsPhone> getPhones() {
    return phones;
  }

  /**
   * Required. Phone numbers that this agent may use when placing a verified call. Only add / remove
   * actions are allowed. Each action will be reviewed before the change takes place.
   * @param phones phones or {@code null} for none
   */
  @com.google.errorprone.annotations.CanIgnoreReturnValue
  public VerifiedCallsAgent setPhones(java.util.List<VerifiedCallsPhone> phones) {
    this.phones = phones;
    return this;
  }

  @Override
  public VerifiedCallsAgent set(String fieldName, Object value) {
    return (VerifiedCallsAgent) super.set(fieldName, value);
  }

  @Override
  public VerifiedCallsAgent clone() {
    return (VerifiedCallsAgent) super.clone();
  }

}
